run:
  timeout: 5m

linters:
  enable:
    - errcheck          
    - gosimple          
    - govet             
    - ineffassign       
    - staticcheck       
    - unused            
    - gofmt
    - goimports
    - gci
    - misspell
    - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false



